---
# deploy production machine for live use

- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - deploy
    - services
  vars_prompt:
    - name: commit
      prompt: Branch to deploy
      default: master
      private: no
